apiVersion: v1
kind: ConfigMap
metadata:
  name: music-config
  namespace: music-app
data:
  # MySQL Configuration
  MYSQL_DATABASE: "music"
  MYSQL_USER: "musicuser"
  
  # Spring Boot Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_PORT: "8084"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: "tuneupcontakt@gmail.com"
  
  # Frontend Configuration
  VITE_BASE_PATH: "/"

