apiVersion: v1
kind: Secret
metadata:
  name: music-secrets
  namespace: music-app
type: Opaque
stringData:
  # MySQL Secrets
  MYSQL_ROOT_PASSWORD: "Saivarun@123"
  MYSQL_PASSWORD: "musicpass"
  
  # Spring Boot Database Secrets
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "Saivarun@123"
  
  # Spring Boot Mail Secrets
  SPRING_MAIL_PASSWORD: "izxl eawx havp cafu"

